plugins {
    id 'java'
    id("com.gradleup.shadow") version "9.1.0"
    id 'maven-publish'
}


group = 'com.reider745.proxy.zotecore'
version = '1.1-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = "innercoreReleases"
        url = uri("https://maven.inner-core.org/releases")
    }
}

dependencies {
    implementation(project(":common"))
    compileOnly("org.innercore.zotecoreloader:ZoteCoreLoader:beta-1.1.1")
}


tasks.build {
    dependsOn(tasks.shadowJar)
}

tasks.jar {
    archiveFileName.set("${project.name}-${project.version}.jar")
}

publishing {
    publications {
        maven(MavenPublication) {
            artifact(shadowJar) {
                classifier = null
            }
        }
    }

    repositories {
        maven {
            name = "innerCoreReposiliteReleases"
            url = uri("https://maven.inner-core.org/releases")
            credentials {
                username = findProperty('innercoreUsername')?.toString() ?: System.getenv('MAVEN_USERNAME')
                password = findProperty('innercorePassword')?.toString() ?: System.getenv('MAVEN_PASSWORD')
            }
        }
    }
}