plugins {
    id 'java'
}

group = 'com.reider745'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()

    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }
}

dependencies {
    compileOnly('org.projectlombok:lombok:1.18.42')
    annotationProcessor('org.projectlombok:lombok:1.18.42')

    compileOnly("org.jetbrains:annotations:26.0.2-1")
    annotationProcessor("org.jetbrains:annotations:26.0.2-1")

    implementation("fastutil:fastutil:5.0.9")
    implementation("io.nats:jnats:2.25.3")
}